// ============================================================
//  CHRONO-BREVET — BASE DE QUESTIONS
//  Modifie, ajoute ou supprime des questions ici librement.
//  Format d'une question :
//  {
//    "theme"     : "Nom du thème (apparaît dans le menu)",
//    "evenement" : "Intitulé court de l'événement",
//    "question"  : "La question posée à l'élève",
//    "reponse"   : "La réponse EXACTE attendue",
//    "format"    : "annee" | "mois" | "precis" | "double",
//    "temps"     : durée en secondes (ex: 15, 20, 30),
//    "explication": "Explication affichée après la réponse"
//  }
// ============================================================

const databaseQuestions = [
    // --- LA PREMIÈRE GUERRE MONDIALE ---
    { "theme": "La Première Guerre mondiale", "evenement": "L'assassinat de l'archiduc François-Ferdinand à Sarajevo", "question": "À quelle date précise a eu lieu l'assassinat de l'archiduc François-Ferdinand à Sarajevo ?", "reponse": "28 juin 1914", "format": "precis", "temps": 30, "explication": "Le 28 juin 1914, cet événement déclenche l'engrenage des alliances." },
    { "theme": "La Première Guerre mondiale", "evenement": "La déclaration de guerre de l'Allemagne à la France", "question": "À quelle date précise l'Allemagne déclare-t-elle la guerre à la France (début officiel) ?", "reponse": "3 août 1914", "format": "precis", "temps": 30, "explication": "Le 3 août 1914 marque l'entrée officielle de la France dans le premier conflit mondial." },
    { "theme": "La Première Guerre mondiale", "evenement": "Le début de la guerre de positions (les tranchées)", "question": "En quel mois et quelle année débute la guerre de positions (les tranchées) ?", "reponse": "novembre 1914", "format": "mois", "temps": 20, "explication": "C'est en novembre 1914 que le front se stabilise et que les soldats s'enterrent." },
    { "theme": "La Première Guerre mondiale", "evenement": "La bataille de Verdun", "question": "En quelle année s'est déroulée la dramatique bataille de Verdun ?", "reponse": "1916", "format": "annee", "temps": 15, "explication": "La bataille de Verdun a eu lieu de février à décembre 1916, restant le symbole de la guerre d'usure." },
    { "theme": "La Première Guerre mondiale", "evenement": "Les révolutions bolcheviques en Russie", "question": "En quelle année ont eu lieu les révolutions bolcheviques en Russie ?", "reponse": "1917", "format": "annee", "temps": 15, "explication": "En 1917 (février et octobre), provoquant la chute du Tsar et la prise de pouvoir de Lénine." },
    { "theme": "La Première Guerre mondiale", "evenement": "L'entrée en guerre des États-Unis", "question": "En quelle année les États-Unis entrent-ils en guerre ?", "reponse": "1917", "format": "annee", "temps": 15, "explication": "L'entrée en guerre des États-Unis en 1917 apporte un soutien humain et matériel décisif à l'Entente." },
    { "theme": "La Première Guerre mondiale", "evenement": "La signature de l'Armistice à Rethondes", "question": "À quelle date précise est signé l'Armistice de la Grande Guerre ?", "reponse": "11 novembre 1918", "format": "precis", "temps": 30, "explication": "L'armistice est signé le 11 novembre 1918, mettant fin aux combats." },
    { "theme": "La Première Guerre mondiale", "evenement": "La signature du Traité de Versailles", "question": "À quelle date précise est signé le Traité de Versailles ?", "reponse": "28 juin 1919", "format": "precis", "temps": 30, "explication": "Le 28 juin 1919, ce traité établit la paix officielle mais pénalise l'Allemagne." },

    // --- L'ENTRE-DEUX-GUERRES ---
    { "theme": "L'entre-deux-guerres", "evenement": "La prise du pouvoir par Mussolini en Italie", "question": "En quelle année Mussolini prend-il le pouvoir en Italie ?", "reponse": "1922", "format": "annee", "temps": 15, "explication": "En 1922, à la suite de la marche sur Rome, le fascisme s'installe." },
    { "theme": "L'entre-deux-guerres", "evenement": "La mort de Lénine / Début de Staline", "question": "En quelle année meurt Lénine, marquant le début de l'ère de Staline ?", "reponse": "1924", "format": "annee", "temps": 15, "explication": "La mort de Lénine en 1924 permet à Staline de prendre progressivement le contrôle total de l'URSS." },
    { "theme": "L'entre-deux-guerres", "evenement": "Le Krach boursier de Wall Street", "question": "En quel mois et quelle année a lieu le Krach boursier de Wall Street (crise économique) ?", "reponse": "octobre 1929", "format": "mois", "temps": 20, "explication": "En octobre 1929 ('Jeudi noir'), déclenchant une crise économique mondiale majeure." },
    { "theme": "L'entre-deux-guerres", "evenement": "La nomination d'Hitler comme chancelier", "question": "À quelle date précise Hitler devient-il chancelier en Allemagne ?", "reponse": "30 janvier 1933", "format": "precis", "temps": 30, "explication": "Il est nommé légalement chancelier par le président Hindenburg le 30 janvier 1933." },
    { "theme": "L'entre-deux-guerres", "evenement": "Les lois antisémites de Nuremberg", "question": "En quelle année sont proclamées les lois antisémites de Nuremberg ?", "reponse": "1935", "format": "annee", "temps": 15, "explication": "En 1935, le régime nazi exclut juridiquement les Juifs de la citoyenneté allemande." },
    { "theme": "L'entre-deux-guerres", "evenement": "La Nuit de Cristal", "question": "En quelle année s'est déroulée la Nuit de Cristal ?", "reponse": "1938", "format": "annee", "temps": 15, "explication": "En 1938, un grand pogrom violent orchestré par l'État cible la population juive en Allemagne." },
    { "theme": "L'entre-deux-guerres", "evenement": "Les Accords de Munich", "question": "En quelle année sont signés les Accords de Munich ?", "reponse": "1938", "format": "annee", "temps": 15, "explication": "En 1938, face aux exigences territoriales de l'Allemagne d'Hitler qui annexe les Sudètes." },
    { "theme": "L'entre-deux-guerres", "evenement": "La Guerre d'Espagne", "question": "Quelles sont les années de début et de fin de la Guerre d'Espagne ?", "reponse": "1936-1939", "format": "double", "temps": 20, "explication": "Ce conflit majeur de l'entre-deux-guerres s'étend de 1936 à 1939 et sert de prélude mondial." },
    { "theme": "L'entre-deux-guerres", "evenement": "Le Front Populaire au pouvoir en France", "question": "Quelles sont les années de début et de fin de l'expérience du Front Populaire au gouvernement ?", "reponse": "1936-1938", "format": "double", "temps": 20, "explication": "De 1936 à 1938, mené par Léon Blum, instaurant notamment les congés payés et la semaine de 40 heures." },
    { "theme": "L'entre-deux-guerres", "evenement": "Les Grandes purges staliniennes en URSS", "question": "Quelles sont les années clés des Grandes purges staliniennes en URSS ?", "reponse": "1936-1938", "format": "double", "temps": 20, "explication": "La terreur de masse et les procès truqués staliniens frappent particulièrement de 1936 à 1938." },
    { "theme": "L'entre-deux-guerres", "evenement": "Le Pacte germano-soviétique", "question": "En quelle année est signé le Pacte germano-soviétique ?", "reponse": "1939", "format": "annee", "temps": 15, "explication": "Le 23 août 1939, un pacte de non-agression surprise est conclu entre l'Allemagne et l'URSS." },

    // --- LA SECONDE GUERRE MONDIALE ---
    { "theme": "La Seconde Guerre mondiale", "evenement": "La Seconde Guerre mondiale", "question": "Quelles sont les années de début et de fin de la Seconde Guerre mondiale ?", "reponse": "1939-1945", "format": "double", "temps": 20, "explication": "Le conflit s'ouvre le 1er septembre 1939 avec l'invasion de la Pologne et s'achève en septembre 1945." },
    { "theme": "La Seconde Guerre mondiale", "evenement": "L'invasion de la Pologne", "question": "En quelle année l'Allemagne envahit-elle la Pologne, déclenchant la guerre ?", "reponse": "1939", "format": "annee", "temps": 15, "explication": "L'invasion de la Pologne par l'Allemagne débute le 1er septembre 1939." },
    { "theme": "La Seconde Guerre mondiale", "evenement": "L'Appel du général de Gaulle à la BBC", "question": "À quelle date précise de Gaulle lance-t-il son Appel à la résistance depuis Londres ?", "reponse": "18 juin 1940", "format": "precis", "temps": 30, "explication": "Le 18 juin 1940 sur les ondes de la BBC, fondant la France Libre." },
    { "theme": "La Seconde Guerre mondiale", "evenement": "Les pleins pouvoirs au maréchal Pétain", "question": "En quelle année Pétain reçoit-il les pleins pouvoirs ?", "reponse": "1940", "format": "annee", "temps": 15, "explication": "Le 10 juillet 1940, à la suite de la défaite nationale, mettant fin à la IIIe République." },
    { "theme": "La Seconde Guerre mondiale", "evenement": "Le Régime de Vichy au pouvoir", "question": "Quelles sont les années de début et de fin du Régime de Vichy ?", "reponse": "1940-1944", "format": "double", "temps": 20, "explication": "Le régime autoritaire de collaboration dirigé par Pétain dure de 1940 à 1944." },
    { "theme": "La Seconde Guerre mondiale", "evenement": "L'invasion de l'URSS (Opération Barbarossa)", "question": "En quelle année l'Allemagne lance-t-elle l'invasion de l'URSS ?", "reponse": "1941", "format": "annee", "temps": 15, "explication": "L'attaque surprise (Opération Barbarossa) est déclenchée le 22 juin 1941." },
    { "theme": "La Seconde Guerre mondiale", "evenement": "L'attaque de Pearl Harbor", "question": "En quelle année a lieu l'attaque japonaise sur Pearl Harbor ?", "reponse": "1941", "format": "annee", "temps": 15, "explication": "Le 7 décembre 1941, provoquant l'entrée immédiate en guerre des États-Unis." },
    { "theme": "La Seconde Guerre mondiale", "evenement": "La Conférence de Wannsee (Solution finale)", "question": "En quelle année se tient la Conférence de Wannsee ?", "reponse": "1942", "format": "annee", "temps": 15, "explication": "En janvier 1942, organisation administrative et méthodique de l'extermination des Juifs d'Europe." },
    { "theme": "La Seconde Guerre mondiale", "evenement": "La Rafle du Vél d'Hiv", "question": "En quelle année se déroule la Rafle du Vél d'Hiv ?", "reponse": "1942", "format": "annee", "temps": 15, "explication": "En juillet 1942, la plus grande arrestation massive de Juifs en France par la police française." },
    { "theme": "La Seconde Guerre mondiale", "evenement": "La fin de la bataille de Stalingrad", "question": "Quelles sont les années de début et de fin de la bataille de Stalingrad, tournant majeur de la guerre à l'Est ?", "reponse": "1942-1943", "format": "double", "temps": 20, "explication": "En février 1943, la capitulation de la VIe armée allemande marque le grand tournant de la guerre à l'Est." },
    { "theme": "La Seconde Guerre mondiale", "evenement": "L'instauration du STO (Service du Travail Obligatoire)", "question": "En quelle année est instauré le STO en France ?", "reponse": "1943", "format": "annee", "temps": 15, "explication": "En 1943, réquisitionnant les jeunes Français pour travailler au profit de l'Allemagne." },
    { "theme": "La Seconde Guerre mondiale", "evenement": "La création du CNR (Conseil National de la Résistance)", "question": "En quelle année est créé le CNR par Jean Moulin ?", "reponse": "1943", "format": "annee", "temps": 15, "explication": "En mai 1943, afin d'unifier les différents mouvements de résistance intérieure." },
    { "theme": "La Seconde Guerre mondiale", "evenement": "La création de la Milice française", "question": "En quelle année est créée la Milice française ?", "reponse": "1943", "format": "annee", "temps": 15, "explication": "En 1943, cette organisation fasciste collabore activement avec la Gestapo contre la Résistance." },
    { "theme": "La Seconde Guerre mondiale", "evenement": "Le Débarquement allié en Normandie", "question": "À quelle date précise a lieu le Débarquement allié en Normandie ?", "reponse": "6 juin 1944", "format": "precis", "temps": 30, "explication": "Le 6 juin 1944 (D-Day), ouvrant le second front à l'Ouest pour libérer l'Europe." },
    { "theme": "La Seconde Guerre mondiale", "evenement": "Le droit de vote accordé aux femmes en France", "question": "En quelle année les femmes obtiennent-elles le droit de vote en France ?", "reponse": "1944", "format": "annee", "temps": 15, "explication": "En avril 1944, par ordonnance du GPRF du général de Gaulle, une avancée démocratique majeure." },
    { "theme": "La Seconde Guerre mondiale", "evenement": "Le début de l'Épuration", "question": "En quelle année débute l'Épuration à la Libération ?", "reponse": "1944", "format": "annee", "temps": 15, "explication": "L'Épuration commence dès la Libération du territoire, au cours de l'été et de l'automne 1944." },
    { "theme": "La Seconde Guerre mondiale", "evenement": "La capitulation de l'Allemagne nazie", "question": "À quelle date précise capitule l'Allemagne nazie ?", "reponse": "8 mai 1945", "format": "precis", "temps": 30, "explication": "La capitulation sans condition signée à Berlin met fin aux combats sur le continent européen." },
    { "theme": "La Seconde Guerre mondiale", "evenement": "La création de l'ONU", "question": "En quelle année est créée l'ONU ?", "reponse": "1945", "format": "annee", "temps": 15, "explication": "Par la charte de San Francisco signée le 26 juin 1945 pour maintenir la paix future dans le monde." },
    { "theme": "La Seconde Guerre mondiale", "evenement": "Les bombardements atomiques de Hiroshima et Nagasaki", "question": "En quelle année sont larguées les bombes atomiques sur Hiroshima et Nagasaki ?", "reponse": "1945", "format": "annee", "temps": 15, "explication": "En août 1945, l'usage de l'arme nucléaire précipite la fin absolue du conflit mondial." },
    { "theme": "La Seconde Guerre mondiale", "evenement": "La capitulation officielle du Japon", "question": "À quelle date précise capitule le Japon, clôturant le conflit ?", "reponse": "2 septembre 1945", "format": "precis", "temps": 30, "explication": "Le 2 septembre 1945 marque l'arrêt définitif complet de la Seconde Guerre mondiale." },
    { "theme": "La Seconde Guerre mondiale", "evenement": "Le début du Procès de Nuremberg", "question": "En quelle année débute le Procès de Nuremberg ?", "reponse": "1945", "format": "annee", "temps": 15, "explication": "À l'automne 1945 pour juger les hauts responsables nazis et définir les crimes contre l'humanité." },

    // --- GUERRE FROIDE ET MONDE APRÈS 1945 ---
    { "theme": "Guerre froide", "evenement": "Le lancement du Plan Marshall", "question": "En quelle année est lancé le Plan Marshall, amorçant la Guerre froide ?", "reponse": "1947", "format": "annee", "temps": 15, "explication": "En 1947, cette aide financière américaine vise à reconstruire l'Europe et endiguer le communisme." },
    { "theme": "Guerre froide", "evenement": "Le blocus de Berlin / Création d'Israël / DUDH", "question": "En quelle année a lieu le blocus de Berlin, la création d'Israël et la Déclaration universelle des droits de l'homme ?", "reponse": "1948", "format": "annee", "temps": 15, "explication": "L'année 1948 cumule ces trois jalons historiques mondiaux." },
    { "theme": "Guerre froide", "evenement": "La création de l'OTAN / Division de l'Allemagne", "question": "En quelle année est créée l'OTAN et s'opère la division de l'Allemagne (RFA / RDA) ?", "reponse": "1949", "format": "annee", "temps": 15, "explication": "En 1949, marquée aussi par l'accès à la bombe A par l'URSS et la victoire de Mao en Chine." },
    { "theme": "Guerre froide", "evenement": "Le début de la construction du mur de Berlin", "question": "En quelle année commence la construction du mur de Berlin ?", "reponse": "1961", "format": "annee", "temps": 15, "explication": "Le 13 août 1961, barrant hermétiquement le passage entre l'Est et l'Ouest." },
    { "theme": "Guerre froide", "evenement": "La Crise des missiles de Cuba", "question": "En quelle année éclate la dangereuse Crise des missiles de Cuba ?", "reponse": "1962", "format": "annee", "temps": 15, "explication": "En octobre 1962, le point culminant et le plus proche d'un conflit nucléaire direct USA/URSS." },
    { "theme": "Guerre froide", "evenement": "L'assassinat de John F. Kennedy", "question": "En quelle année le président américain Kennedy est-il assassiné ?", "reponse": "1963", "format": "annee", "temps": 15, "explication": "Le 22 novembre 1963 à Dallas au Texas." },
    { "theme": "Guerre froide", "evenement": "La Guerre du Vietnam", "question": "Quelles sont les années de l'intervention militaire massive des États-Unis au Vietnam ?", "reponse": "1964-1975", "format": "double", "temps": 20, "explication": "Ce conflit majeur de la Guerre froide impliquant l'armée américaine s'étend de 1964 à 1975." },
    { "theme": "Guerre froide", "evenement": "La chute du mur de Berlin", "question": "En quelle année tombe le mur de Berlin ?", "reponse": "1989", "format": "annee", "temps": 15, "explication": "Le 9 novembre 1989, symbole de l'effondrement du bloc communiste et de la réunification." },
    { "theme": "Guerre froide", "evenement": "L'éclatement de l'URSS", "question": "En quelle année éclate l'URSS, clôturant la Guerre froide ?", "reponse": "1991", "format": "annee", "temps": 15, "explication": "En décembre 1991, la démission de Gorbatchev scelle la disparition officielle de l'Union Soviétique." },
    { "theme": "Décolonisation", "evenement": "La défaite française de Diên Biên Phu", "question": "En quelle année a lieu la défaite française de Diên Biên Phu (Indochine) ?", "reponse": "1954", "format": "annee", "temps": 15, "explication": "En mai 1954, scellant l'indépendance du Vietnam et la fin de l'Indochine française." },
    { "theme": "Décolonisation", "evenement": "La Guerre d'Algérie", "question": "Quelles sont les années de début et de fin de la Guerre d'Algérie ?", "reponse": "1954-1962", "format": "double", "temps": 20, "explication": "Le conflit colonial majeur s'étend de la Toussaint rouge en 1954 jusqu'à l'été 1962." },
    { "theme": "Décolonisation", "evenement": "L'indépendance de l'Algérie", "question": "En quelle année l'Algérie proclame-t-elle officiellement son indépendance ?", "reponse": "1962", "format": "annee", "temps": 15, "explication": "En 1962, matérialisée par les accords d'Évian en mars et le référendum d'autodétermination en juillet." },
    { "theme": "Histoire récente", "evenement": "Le Génocide des Tutsi au Rwanda", "question": "En quelle année a lieu le terrible Génocide au Rwanda ?", "reponse": "1994", "format": "annee", "temps": 15, "explication": "Le génocide contre les Tutsi s'est produit d'avril à juillet 1994, faisant près d'un million de victimes." },
    { "theme": "Histoire récente", "evenement": "Les attentats du 11 septembre", "question": "En quelle année se produisent les attentats terroristes du 11 septembre aux États-Unis ?", "reponse": "2001", "format": "annee", "temps": 15, "explication": "En 2001, frappant de plein fouet les tours du World Trade Center et le Pentagone." },
    { "theme": "Histoire récente", "evenement": "L'invasion de l'Irak par les États-Unis", "question": "En quelle année les États-Unis envahissent-ils l'Irak ?", "reponse": "2003", "format": "annee", "temps": 15, "explication": "L'invasion militaire coalisée américaine débute au printemps 2003." },

    // --- CONSTRUCTION EUROPÉENNE ---
    { "theme": "Construction européenne", "evenement": "La création de la CECA", "question": "En quelle année est créée la CECA ?", "reponse": "1951", "format": "annee", "temps": 15, "explication": "En 1951, la Communauté européenne du charbon et de l'acier lance l'intégration économique européenne." },
    { "theme": "Construction européenne", "evenement": "La signature du Traité de Rome (CEE)", "question": "En quelle année est signé le Traité de Rome fondant la CEE ?", "reponse": "1957", "format": "annee", "temps": 15, "explication": "En 1957, jetant les bases d'un grand marché commun entre six États fondateurs." },
    { "theme": "Construction européenne", "evenement": "La signature du Traité de Maastricht (UE)", "question": "En quelle année est signé le Traité de Maastricht créant l'Union européenne ?", "reponse": "1992", "format": "annee", "temps": 15, "explication": "Signé en 1992, il institue l'Union européenne, la citoyenneté européenne et prépare la monnaie unique." },
    { "theme": "Construction européenne", "evenement": "La mise en circulation des billets et pièces en Euro", "question": "En quelle année l'euro fiduciaire est-il officiellement mis en circulation ?", "reponse": "2002", "format": "annee", "temps": 15, "explication": "Le 1er janvier 2002, les pièces et billets arrivent concrètement dans le quotidien des citoyens." },

    // --- INSTITUTIONS ET SOCIÉTÉ FRANÇAISE ---
    { "theme": "Institutions françaises", "evenement": "L'adoption de la Constitution de la IVe République", "question": "En quelle année est adoptée la Constitution de la IVe République ?", "reponse": "1946", "format": "annee", "temps": 15, "explication": "En 1946, installant un régime parlementaire fort après le conflit mondial." },
    { "theme": "La Ve République", "evenement": "L'adoption de la Constitution de la Ve République", "question": "En quelle année est adoptée la Constitution de la Ve République ?", "reponse": "1958", "format": "annee", "temps": 15, "explication": "En septembre/octobre 1958, portée par de Gaulle au milieu de la crise algérienne, créant nos institutions actuelles." },
    { "theme": "La Ve République", "evenement": "L'instauration du suffrage universel direct pour l'élection présidentielle", "question": "En quelle année l'élection du président au suffrage universel direct est-elle instaurée ?", "reponse": "1962", "format": "annee", "temps": 15, "explication": "En 1962, à la suite d'une révision constitutionnelle approuvée par les Français par référendum." },
    { "theme": "La Ve République", "evenement": "La première alternance politique de la Ve / Élection de Mitterrand", "question": "En quelle année se produit la première alternance politique avec l'élection de François Mitterrand ?", "reponse": "1981", "format": "annee", "temps": 15, "explication": "En mai 1981, la gauche accède pour la première fois à la présidence sous la Ve République." },
    { "theme": "La Ve République", "evenement": "L'abolition de la peine de mort en France", "question": "En quelle année la peine de mort est-elle définitivement abolie en France ?", "reponse": "1981", "format": "annee", "temps": 15, "explication": "Le 9 octobre 1981, un combat politique et moral majeur porté par le garde des Sceaux Robert Badinter." },
    { "theme": "La Ve République", "evenement": "Le passage au quinquennat présidentiel", "question": "En quelle année la France adopte-t-elle le quinquennat présidentiel ?", "reponse": "2000", "format": "annee", "temps": 15, "explication": "Le mandat présidentiel passe de 7 à 5 ans suite au vote par référendum des citoyens à l'an 2000." },
    { "theme": "Société française", "evenement": "L'autonomie financière et professionnelle des femmes mariées", "question": "Depuis quelle année les femmes peuvent-elles travailler ou ouvrir un compte sans l'accord de leur mari ?", "reponse": "1965", "format": "annee", "temps": 15, "explication": "Une loi de juillet 1965 émancipe financièrement et professionnellement les femmes mariées en France." },
    { "theme": "Société française", "evenement": "L'instauration de l'autorité parentale conjointe", "question": "En quelle année la notion d'autorité parentale conjointe remplace-t-elle la puissance paternelle ?", "reponse": "1970", "format": "annee", "temps": 15, "explication": "En 1970, la loi supprime le chef de famille au profit d'une égalité des deux parents face à l'enfant." },
    { "theme": "Société française", "evenement": "La Loi Veil sur l'IVG", "question": "En quelle année est votée la Loi Veil sur l'IVG ?", "reponse": "1975", "format": "annee", "temps": 15, "explication": "Adoptée en janvier 1975, dépénalisant l'avortement. C'est aussi l'année de la réforme du divorce par consentement mutuel." },
    { "theme": "Société française", "evenement": "La loi sur la parité en politique", "question": "En quelle année est adoptée la loi sur la parité en politique ?", "reponse": "2000", "format": "annee", "temps": 15, "explication": "En juin 2000, pour encourager et contraindre un égal accès des femmes et des hommes aux mandats électoraux." },
    { "theme": "Société française", "evenement": "La promulgation de la loi sur le Mariage pour tous", "question": "En quelle année est promulguée la loi sur le Mariage pour tous ?", "reponse": "2013", "format": "annee", "temps": 15, "explication": "En mai 2013, ouvrant légalement le droit au mariage et à l'adoption pour les couples de même sexe." },
    { "theme": "Histoire récente", "evenement": "Les attentats terroristes de Paris (Charlie Hebdo / Bataclan)", "question": "En quelle année ont eu lieu les attentats majeurs de janvier et de novembre à Paris ?", "reponse": "2015", "format": "annee", "temps": 15, "explication": "L'année 2015 a été profondément et dramatiquement marquée par ces vagues d'attentats terroristes." }
];
